---
- name: install fail2ban
  become: yes
  package: 
    name: fail2ban

- name: copy sshd fail2ban config
  become: yes
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0664'

- name: copy fail2ban configs
  become: yes
  copy:
    src: files/fail2ban/
    dest: /etc/fail2ban/

- name: restart and enable fail2ban on boot
  become: yes
  service: 
    name: fail2ban
    state: restarted
    enabled: yes