---
- name: install fail2ban
  become: yes
  package: 
    name: fail2ban

- name: copy fail2ban configs
  become: yes
  copy:
    src: files/fail2ban/
    dest: /etc/fail2ban/
  when: copyconfig == "true"

- name: restart and enable fail2ban on boot
  become: yes
  service: 
    name: fail2ban
    state: restarted
    enabled: yes