- name: stop and disable fail2ban on boot
  become: yes
  service: 
    name: fail2ban
    state: stopped
    enabled: no

- name: remove fail2ban
  become: yes
  package: 
    name: fail2ban
    state: absent

- name: remove fail2ban config
  become: yes
  file:
    state: absent
    path: /etc/fail2ban

- name: remove fail2ban service
  become: yes
  file:
    state:  absent
    path: /etc/systemd/system/fail2ban.service

- name: running systemd daemon-reload
  become: yes
  service: 
    daemon_reload: yes